
#ifndef HD_APPLICATIONS_SMARTGO_HD_INC_SMARTGO_TYPES_H_
#define HD_APPLICATIONS_SMARTGO_HD_INC_SMARTGO_TYPES_H_

#define APPL_SMARTGO_ERR_BAD_PARAMETER         (int32_t)(-0x989681) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_BAD_PARAMETER)
#define APPL_SMARTGO_ERR_OUT_OF_MEMORY         (int32_t)(-0x989682) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_OUT_OF_MEMORY)
#define APPL_SMARTGO_ERR_ALREADY_INITIALIZED   (int32_t)(-0x989683) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_ALREADY_INITIALIZED)
#define APPL_SMARTGO_ERR_NOT_INITIALIZED       (int32_t)(-0x989684) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_NOT_INITIALIZED)
#define APPL_SMARTGO_ERR_FEATURE_NOT_SUPPORTED (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_FEATURE_NOT_SUPPORTED)
#define APPL_SMARTGO_ERR_TIMEOUT               (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_TIMEOUT)
#define APPL_SMARTGO_ERR_DEVICE_BUSY           (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_DEVICE_BUSY)
#define APPL_SMARTGO_ERR_INVALID_HANDLE        (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_INVALID_HANDLE)
#define APPL_SMARTGO_ERR_SEMAPHORE_CREATE      (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_SEMAPHORE_CREATE)
#define APPL_SMARTGO_ERR_UNSUPPORTED_VERSION   (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_UNSUPPORTED_VERSION)
#define APPL_SMARTGO_ERR_NOT_OPEN              (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_NOT_OPEN)
#define APPL_SMARTGO_ERR_ALREADY_OPEN          (int32_t)(-1) //APPLICATION_SMARTGO_MODULE_BASE + FAPI_ERR_ALREADY_OPEN)

#define SMARTGO_FGS_ERR_BAD_PARAMETER           (int32_t)(-10000001) //APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_BAD_PARAMETER)
#define SMARTGO_FGS_ERR_OUT_OF_MEMORY           (int32_t)(-10002002) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_OUT_OF_MEMORY)
#define SMARTGO_FGS_ERR_ALREADY_INITIALIZED     (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_ALREADY_INITIALIZED)
#define SMARTGO_FGS_ERR_NOT_INITIALIZED         (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_NOT_INITIALIZED)
#define SMARTGO_FGS_ERR_FEATURE_NOT_SUPPORTED   (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_FEATURE_NOT_SUPPORTED)
#define SMARTGO_FGS_ERR_TIMEOUT                 (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_TIMEOUT)
#define SMARTGO_FGS_ERR_DEVICE_BUSY             (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_DEVICE_BUSY)
#define SMARTGO_FGS_ERR_INVALID_HANDLE          (int32_t)(-0x989E58/*10002008*/) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_INVALID_HANDLE)
#define SMARTGO_FGS_ERR_SEMAPHORE_CREATE        (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_SEMAPHORE_CREATE)
#define SMARTGO_FGS_ERR_UNSUPPORTED_VERSION     (int32_t)(-1) //(APPL_SMARTGO_FGS_ERR_BASE + FAPI_ERR_UNSUPPORTED_VERSION)
#define SMARTGO_FGS_ERR_PROHIBITED              (int32_t)(-0x989EB5) //(APPL_SMARTGO_FGS_ERR_BASE-101)
#define SMARTGO_FGS_ERR_RESOURCES               (int32_t)(-0x989eb6) //(APPL_SMARTGO_FGS_ERR_BASE-102)

typedef enum
{
    FFALSE = 0,
    FTRUE

} fbool_t;


#if 0//def APPL_DEBUG_MODE
    #define FSTATIC
#else
    #define FSTATIC static
#endif


#define DBG_Assert(a)                                            \
    do                                                           \
    {                                                            \
        if ( !(a) )                                              \
        {                                                        \
            FAPI_SYS_PRINT_MSG("ASSERTION FAILED at %s, l.%i\n", \
                              __FILE__ ,__LINE__ );              \
            /*RTOS_ExitApplication*/rtos_halt(-1);                            \
        }                                                        \
    } while (0)                                                  \


#endif /* HD_APPLICATIONS_SMARTGO_HD_INC_SMARTGO_TYPES_H_ */
